Update setup.py to read requirements.txt files
ralphg6/david pull request #69
Opened 2020-02-12 18:57 UTC by arthurTemporim

Closes #68

2020-02-18 15:11 UTC, arthurTemporim commented
On this PR a simple update into documentation was added too with tests content.

2020-02-19 22:41 UTC, ralphg6 approved these changes

2020-02-20 02:28 UTC, ralphg6 requested changes
Why you duplicate README.md?

2020-02-20 02:28 UTC, ralphg6 commented on david/README.md
> +# David
Why you duplicate README.md?

2020-02-21 12:11 UTC, arthurTemporim commented on david/README.md
> +# David
It is not needed, I removed it.

2020-02-21 19:02 UTC, ralphg6 approved these changes

2020-02-21 19:02 UTC, merged